---
#
# Static website
#
apiVersion: v1
kind: Service
metadata:
  name: radar
spec:
  ports:
  - port: 8080
  selector:
    app: radar
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: radar
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: radar
    spec:
      containers:
      - name: radar
        image: andimiller/ratting-radar-server:0.1
        ports:
        - containerPort: 8080
          protocol: "TCP"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
---
#
# Routing
#
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: radar-tls
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - radar.inyour.space
    secretName: radar-tls
  rules:
  - host: radar.inyour.space
    http:
      paths:
      - path: /
        backend:
          serviceName: radar
          servicePort: 8080

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: radar
  annotations:
    # kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: radar.inyour.space
    http:
      paths:
      - path: /
        backend:
          serviceName: radar
          servicePort: 8080
